# Generated by Django 3.2 on 2021-04-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_digits_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digits',
            old_name='result',
            new_name='result1',
        ),
        migrations.RenameField(
            model_name='digits',
            old_name='score',
            new_name='score1',
        ),
        migrations.AddField(
            model_name='digits',
            name='result2',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='digits',
            name='score2',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
